# Generated by Django 4.1.3 on 2022-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('detail_address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('image_url', models.TextField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='SUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('password', models.TextField()),
                ('point', models.IntegerField()),
            ],
            options={
                'db_table': 's_users',
            },
        ),
    ]
