# Generated by Django 4.1.3 on 2022-11-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'b_users',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('ip_address', models.TextField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'View',
            },
        ),
    ]
